### ISSUE TITLE
Problem parsing LHE file due to unrecognized character

### ISSUE THREAD

**Issue by diptaparna** [AndreasAlbert/lhereader#5]
Line no. 2818 of `MG5_aMC_v2_7_3/madgraph/various/banner.py` contains the `'\a'` character -
`%(sys_alpsfact)s = sys_alpsfact  # \alpha_s emission scale factors`

Due to this, the produced LHE file also contains this `'\a'` character, causing the XML parser to crash with an uncaught exception.

**Comment by AndreasAlbert** [comment]
Hi @diptaparna thanks for reporting. Would you have a small example file that I can replicate the problem with?

**Comment by diptaparna** [comment]
[unweighted_events.lhe.gz](https://github.com/AndreasAlbert/lhereader/files/7390592/unweighted_events.lhe.gz)
![Screenshot from 2021-10-21 23-55-56](https://user-images.githubusercontent.com/11439814/138304177-7d5ecbc4-3875-48d8-ad66-607c44f612d0.png)

**Comment by diptaparna** [comment]
Hi, is there any update so far? Do you need any other information?

**Comment by AndreasAlbert** [comment]
I tried circumventing this problem, but there does not seem to be a reasonable way to do it within xml parsing. Unless there is a handle that I missed, the best approach here is to manually remove the offending character (e.g. using a one-line sed command) before parsing the file. Let me know if you have an implementation suggestion.
